# Generated by Django 6.0.6 on 2026-06-22 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('user', 'skill')},
        ),
        migrations.AlterField(
            model_name='skill',
            name='progress',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='created_at',
        ),
    ]
