# Generated by Django 6.0.6 on 2026-06-18 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=150)),
                ('career_path', models.CharField(choices=[('AI/ML Engineer', 'AI/ML Engineer'), ('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer'), ('Full Stack Developer', 'Full Stack Developer'), ('Data Scientist', 'Data Scientist')], max_length=100)),
                ('readiness', models.FloatField(default=0)),
                ('experience_level', models.CharField(default='Fresher', max_length=50)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('demand_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Very High', 'Very High')], default='Medium', max_length=20)),
                ('missing_skills', models.JSONField(default=list)),
                ('recommended_courses', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
