 import { useEffect, useState } from "react";
import MainLayout from "../layouts/MainLayout";
import api from "../services/api";

import StatCard from "../components/StatCard";
import ReadinessChart from "../components/ReadinessChart";
import JobComparisonTable from "../components/JobComparisonTable";
import {
  FaFileAlt,
  FaChartLine,
  FaBrain,
  FaBriefcase,} from "react-icons/fa";

function Reports() {
  const [coach, setCoach] = useState(null);
  const [jobs, setJobs] = useState([]);

  useEffect(() => {
    Promise.all([
      api.get("career-coach/"),
      api.get("job-recommendations/"),
    ])
      .then(([coachRes, jobsRes]) => {
        setCoach(coachRes.data);
        setJobs(jobsRes.data);
      })
      .catch(console.error);
  }, []);

  if (!coach) {
    return (
      <MainLayout>
        <h2>Loading Report...</h2>
      </MainLayout>
    );
  }

  const topJob =
    jobs.length > 0 ? jobs[0] : null;

  return (
    <MainLayout>
      {/* HERO */}

      <div
        style={{
          background:
            "linear-gradient(135deg,#1E3A8A,#2563EB)",
          color: "white",
          padding: "35px",
          borderRadius: "25px",
          marginBottom: "30px",
        }}
      >
        <h1>
          📊 Career Intelligence Report
        </h1>

        <p
          style={{
            fontSize: "18px",
            opacity: 0.9,
          }}
        >
          Personalized insights
          generated by OrbitX AI
        </p>
      </div>

      {/* KPI CARDS */}

      <div
        style={{
          display: "grid",
          gridTemplateColumns:
            "repeat(auto-fit,minmax(250px,1fr))",
          gap: "20px",
          marginBottom: "30px",
        }}
      >
        <StatCard
          title="Resume Score"
          value={coach.resume_score}
          color="#16A34A"
          icon={<FaFileAlt />}
        />

        <StatCard
          title="Placement Score"
          value={coach.placement_score}
          color="#2563EB"
          icon={<FaChartLine />}
        />

        <StatCard
          title="Career Path"
          value={coach.career_path}
          color="#9333EA"
          icon={<FaBrain />}
        />

        <StatCard
          title="Current Level"
          value={coach.current_level}
          color="#F97316"
          icon={<FaBriefcase />}
        />
      </div>
     

    <div
  style={{
    display: "grid",
    gridTemplateColumns:
      "1fr 1fr",
    gap: "20px",
    marginBottom: "30px",
  }}
>
  <ReadinessChart
    value={coach.placement_score}
  />

  <div
   style={{
    background: "white",
    padding: "25px",
    borderRadius: "20px",
    boxShadow:
      "0 10px 30px rgba(0,0,0,.08)",
  }}>
    <h2>
  🏆 Career Grade
</h2>

<h1
  style={{
    color: "#16A34A",
    fontSize: "70px",
    margin: "10px 0",
  }}
>
  A
</h1>

<div
  style={{
    width: "100%",
    height: "12px",
    background: "#E5E7EB",
    borderRadius: "20px",
    overflow: "hidden",
  }}
>
  <div
    style={{
      width: "82%",
      height: "100%",
      background: "#16A34A",
    }}
  />
</div>

<p
  style={{
    marginTop: "15px",
    color: "#64748B",
  }}
>
  Excellent placement potential
</p>
    
  </div>
</div>

      {/* BEST JOB */}

     <div
  style={{
    display: "grid",
    gridTemplateColumns:
      "1fr 1fr",
    gap: "20px",
    marginBottom: "25px",
  }}
>

  {/* Best Match */}

  {topJob && (
    <div
      style={{
        background: "white",
        padding: "25px",
        borderRadius: "20px",
        boxShadow:
          "0 10px 30px rgba(0,0,0,.08)",
      }}
    >
      <h2>
        🎯 Best Career Match
      </h2>

      <h1
        style={{
          color: "#2563EB",
          marginBottom: "10px",
        }}
      >
        {topJob.job_title}
      </h1>

      <p>
        📈 Readiness:
        {" "}
        {topJob.readiness}%
      </p>

      <p>
        💰 Salary:
        {" "}
        {topJob.salary_range}
      </p>

      <p>
        🚀 Demand:
        {" "}
        {topJob.demand_level}
      </p>
    </div>
  )}

  {/* Priority Skills */}

  <div
    style={{
      background: "white",
      padding: "25px",
      borderRadius: "20px",
      boxShadow:
        "0 10px 30px rgba(0,0,0,.08)",
    }}
  >
    <h2>
      🚨 Priority Skills
    </h2>

    <div
      style={{
        display: "flex",
        gap: "12px",
        flexWrap: "wrap",
        marginTop: "15px",
      }}
    >
      {coach.priority_focus.map(
        (skill) => (
          <span
            key={skill}
            style={{
              background:
                "#FEE2E2",
              color:
                "#DC2626",
              padding:
                "10px 15px",
              borderRadius:
                "999px",
              fontWeight:
                "bold",
            }}
          >
            🔥 {skill}
          </span>
        )
      )}
    </div>
  </div>

</div>

 <JobComparisonTable
  jobs={jobs}
/>

      {/* ORBITX REPORT */}

      <div
        style={{
          background:
            "linear-gradient(135deg,#7C3AED,#9333EA)",
          color: "white",
          padding: "30px",
          borderRadius: "20px",
        }}
      >
        <h2>
          🤖 OrbitX Analysis
        </h2>

        <p
          style={{
            fontSize: "18px",
            lineHeight: "1.8",
          }}
        >
          {coach.placement_advice}
        </p>
      </div>
    </MainLayout>
  );
}

export default Reports;