# Generated by Django 6.0.6 on 2026-06-23 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_branch_profile_career_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_year',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
